import {calculate} from './math.js';
import {recognize,bounds,shapes} from './recognizer.js';
const $=id=>document.getElementById(id),uid=()=>crypto.randomUUID(),clone=v=>structuredClone(v);
const canvas=$('ink'),ctx=canvas.getContext('2d'),viewport=$('viewport'),paper=$('paper');
let doc={id:uid(),title:'考えるためのノート',createdAt:new Date().toISOString(),updatedAt:new Date().toISOString(),pages:[{id:uid(),width:1200,height:1700,background:{type:'grid'},strokes:[],calculations:[]}]};
let settings={touch:false,style:'inline',provider:'local'},db,history=[],future=[],selection=null,tool='pen',color='#20333d',width=2.5,active=null,points=new Map(),pan={x:0,y:0,scale:1},gesture=null,penDown=false,pending=null,requestId=0,abort=null,saveTimer,toastTimer,detailId=null,editId=null,ready=false;
const page=()=>doc.pages[0];
function toast(message){$('toast').textContent=message;$('toast').classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('toast').classList.remove('show'),3500);}
function snapshot(){return{page:clone(page()),selection:clone(selection),title:doc.title};}
function checkpoint(){history.push(snapshot());if(history.length>60)history.shift();future=[];buttons();}
function buttons(){$('undo').disabled=!history.length;$('redo').disabled=!future.length;}
function restore(s){doc.pages[0]=s.page;doc.title=s.title;selection=s.selection;$('title').value=doc.title;syncSettings();draw();renderResults();renderSelection();changed();}
function undo(){cancelOcr();if(!history.length)return;future.push(snapshot());restore(history.pop());buttons();}
function redo(){cancelOcr();if(!future.length)return;history.push(snapshot());restore(future.pop());buttons();}
function changed(){doc.updatedAt=new Date().toISOString();$('empty').hidden=!!(page().strokes.length||page().calculations.length);$('saved').textContent='保存中…';clearTimeout(saveTimer);void save();}
async function openStorage(){try{db=await new Promise((res,rej)=>{const r=indexedDB.open('handwriting-calculation-note',1);r.onupgradeneeded=()=>r.result.createObjectStore('documents');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});const saved=await new Promise((res,rej)=>{let r=db.transaction('documents').objectStore('documents').get('current');r.onsuccess=()=>res(r.result);r.onerror=()=>rej(r.error);});if(saved){validateDocument(saved.doc);doc=saved.doc;settings={...settings,...saved.settings,provider:'local'};}}catch(e){toast('保存データを開けません。バックアップでノートを保護してください。');$('saved').textContent='保存を利用できません';}ready=true;syncSettings();$('title').value=doc.title;draw();renderResults();$('empty').hidden=!!(page().strokes.length||page().calculations.length);buttons();}
async function save(){if(!db){$('saved').textContent='未保存 · バックアップしてください';return false;}try{await new Promise((res,rej)=>{let tx=db.transaction('documents','readwrite');tx.objectStore('documents').put({doc:clone(doc),settings:clone(settings)},'current');tx.oncomplete=res;tx.onerror=()=>rej(tx.error);});$('saved').textContent='この端末に保存済み';return true;}catch{$('saved').textContent='保存に失敗 · バックアップしてください';toast('空き容量やブラウザの保存設定を確認してください。');return false;}}
function syncSettings(){$('touch-write').checked=settings.touch;$('provider').value=settings.provider;$('result-style').value=settings.style;$('background').value=page().background.type;paper.className=page().background.type;$('ocr-state').textContent=settings.provider==='local'?'端末内認識 · 試験版':'Mathpix認識';}
function stroke(s,target=ctx){const p=s.points;if(!p.length)return;target.strokeStyle=s.color;target.fillStyle=s.color;target.lineCap='round';target.lineJoin='round';if(p.length===1){target.beginPath();target.arc(p[0].x,p[0].y,s.width/2,0,Math.PI*2);target.fill();}for(let i=1;i<p.length;i++)segment(p[i-1],p[i],s,target);}
function segment(a,b,s,target=ctx){target.strokeStyle=s.color;target.lineCap='round';target.lineJoin='round';target.lineWidth=s.width*(.5+((a.p??.5)+(b.p??.5))*.5);target.beginPath();target.moveTo(a.x,a.y);target.lineTo(b.x,b.y);target.stroke();}
function draw(){ctx.clearRect(0,0,1200,1700);for(const s of page().strokes)stroke(s);}
function view(){paper.style.transform=`translate(${pan.x}px,${pan.y}px) scale(${pan.scale})`;$('zoom-reset').textContent=Math.round(pan.scale*100)+'%';}
function fit(){pan.scale=Math.min(1,(viewport.clientWidth-36)/1200);pan.x=(viewport.clientWidth-1200*pan.scale)/2;pan.y=24;view();}
function local(e){const r=viewport.getBoundingClientRect();return{x:(e.clientX-r.left-pan.x)/pan.scale,y:(e.clientY-r.top-pan.y)/pan.scale,p:e.pointerType==='pen'?Math.max(.05,e.pressure):.5};}
function setTool(t){tool=t;document.querySelectorAll('[data-tool]').forEach(b=>{b.classList.toggle('active',b.dataset.tool===t);b.setAttribute('aria-pressed',String(b.dataset.tool===t));});canvas.style.cursor=t==='pen'?'crosshair':t==='pan'?'grab':'crosshair';$('hint').textContent=t==='select'?'数式を囲むと自動計算':t==='eraser'?'なぞった筆跡を消す':'ペンで書く · 指で移動';}
function renderSelection(){const g=$('selection-shape');g.replaceChildren();if(!selection)return;const{x,y,w,h}=selection;function el(tag,attrs){const e=document.createElementNS('http://www.w3.org/2000/svg',tag);for(const[k,v]of Object.entries(attrs))e.setAttribute(k,v);g.append(e);}el('rect',{x,y,width:w,height:h,fill:'url(#hatch)',stroke:'#318b87','stroke-width':1.5/pan.scale,'stroke-dasharray':`${5/pan.scale} ${4/pan.scale}`});for(const[p,q]of[[x,y],[x+w,y],[x,y+h],[x+w,y+h]])el('rect',{x:p-5/pan.scale,y:q-5/pan.scale,width:10/pan.scale,height:10/pan.scale,fill:'#fff',stroke:'#318b87','stroke-width':1.5/pan.scale});}
const inside=(p,b)=>p.x>=b.x&&p.x<=b.x+b.w&&p.y>=b.y&&p.y<=b.y+b.h;
function selectedStrokes(area){return page().strokes.filter(s=>{let b=bounds([s]);return b.x+b.w>=area.x&&b.x<=area.x+area.w&&b.y+b.h>=area.y&&b.y<=area.y+area.h;}).map(s=>({...s,points:s.points.filter(p=>inside(p,area))})).filter(s=>s.points.length);}
function erase(p){const r=15/pan.scale;let hit=false;page().strokes=page().strokes.filter(s=>{const found=s.points.some((q,i)=>{if(Math.hypot(p.x-q.x,p.y-q.y)<r)return true;if(!i)return false;const a=s.points[i-1],dx=q.x-a.x,dy=q.y-a.y,t=Math.max(0,Math.min(1,((p.x-a.x)*dx+(p.y-a.y)*dy)/(dx*dx+dy*dy||1)));return Math.hypot(p.x-a.x-t*dx,p.y-a.y-t*dy)<r;});if(found)hit=true;return!found;});if(hit)draw();}
viewport.addEventListener('pointerdown',e=>{if(!ready||e.target.closest('button,input,.result'))return;if(e.pointerType==='touch'&&penDown)return;if(e.pointerType==='pen'){penDown=true;points.clear();gesture=null;if(active?.kind==='pan')active=null;}viewport.setPointerCapture(e.pointerId);points.set(e.pointerId,{x:e.clientX,y:e.clientY});
 if(points.size===2&&!penDown){if(active?.kind==='stroke'){page().strokes.pop();history.pop();draw();buttons();}active=null;const[a,b]=[...points.values()];const rect=viewport.getBoundingClientRect(),mid={x:(a.x+b.x)/2-rect.left,y:(a.y+b.y)/2-rect.top};gesture={distance:Math.hypot(a.x-b.x,a.y-b.y),scale:pan.scale,world:{x:(mid.x-pan.x)/pan.scale,y:(mid.y-pan.y)/pan.scale}};return;}
 if(points.size>1)return;const p=local(e);if(tool==='pan'||(e.pointerType==='touch'&&!settings.touch)){active={kind:'pan',id:e.pointerId,start:{x:e.clientX,y:e.clientY},origin:{...pan}};return;}
 if(tool==='pen'){if(!inside(p,{x:0,y:0,w:1200,h:1700}))return;checkpoint();const s={id:uid(),points:[p],width,color};page().strokes.push(s);active={kind:'stroke',id:e.pointerId,stroke:s};stroke(s);$('empty').hidden=true;}
 else if(tool==='eraser'){checkpoint();active={kind:'erase',id:e.pointerId};erase(p);}
 else if(tool==='select'){cancelOcr();checkpoint();let handle=null;if(selection){const corners=[[selection.x,selection.y],[selection.x+selection.w,selection.y],[selection.x,selection.y+selection.h],[selection.x+selection.w,selection.y+selection.h]];let idx=corners.findIndex(([x,y])=>Math.hypot(p.x-x,p.y-y)<18/pan.scale);if(idx>=0)handle={x:corners[3-idx][0],y:corners[3-idx][1]};}
 if(handle)active={kind:'select',id:e.pointerId,start:handle};else if(selection&&inside(p,selection))active={kind:'move-selection',id:e.pointerId,start:p,origin:{...selection}};else{selection={x:p.x,y:p.y,w:0,h:0};active={kind:'select',id:e.pointerId,start:p};}renderSelection();}
});
viewport.addEventListener('pointermove',e=>{if(!points.has(e.pointerId))return;points.set(e.pointerId,{x:e.clientX,y:e.clientY});if(gesture&&points.size===2){const[a,b]=[...points.values()],r=viewport.getBoundingClientRect();pan.scale=Math.max(.2,Math.min(3,gesture.scale*Math.hypot(a.x-b.x,a.y-b.y)/Math.max(1,gesture.distance)));pan.x=(a.x+b.x)/2-r.left-gesture.world.x*pan.scale;pan.y=(a.y+b.y)/2-r.top-gesture.world.y*pan.scale;view();renderSelection();return;}if(!active||active.id!==e.pointerId)return;const p=local(e);if(active.kind==='stroke'){for(const v of e.getCoalescedEvents?.()||[e]){const q=local(v);if(!inside(q,{x:0,y:0,w:1200,h:1700}))continue;const last=active.stroke.points.at(-1);active.stroke.points.push(q);segment(last,q,active.stroke);}}else if(active.kind==='erase')erase(p);else if(active.kind==='pan'){pan.x=active.origin.x+e.clientX-active.start.x;pan.y=active.origin.y+e.clientY-active.start.y;view();}else if(active.kind==='select'){selection={x:Math.max(0,Math.min(active.start.x,p.x)),y:Math.max(0,Math.min(active.start.y,p.y)),w:Math.abs(p.x-active.start.x),h:Math.abs(p.y-active.start.y)};selection.w=Math.min(selection.w,1200-selection.x);selection.h=Math.min(selection.h,1700-selection.y);renderSelection();}else if(active.kind==='move-selection'){selection={...active.origin,x:Math.max(0,Math.min(1200-active.origin.w,active.origin.x+p.x-active.start.x)),y:Math.max(0,Math.min(1700-active.origin.h,active.origin.y+p.y-active.start.y))};renderSelection();}});
function endPointer(e){if(e.pointerType==='pen')penDown=false;points.delete(e.pointerId);if(gesture){if(points.size<2)gesture=null;active=null;return;}if(!active||active.id!==e.pointerId)return;const kind=active.kind;active=null;if(e.type==='pointercancel'){if(kind==='stroke'||kind==='erase'){const s=history.pop();if(s)restore(s);}renderSelection();buttons();return;}if(kind==='select'||kind==='move-selection'){if(selection.w<8||selection.h<8){selection=null;renderSelection();}else void runRecognition();}if(kind!=='pan')changed();}
viewport.addEventListener('pointerup',endPointer);viewport.addEventListener('pointercancel',endPointer);
viewport.addEventListener('wheel',e=>{e.preventDefault();if(e.ctrlKey||e.metaKey)zoom(pan.scale*Math.exp(-e.deltaY*.006),e.clientX,e.clientY);else{pan.x-=e.deltaX;pan.y-=e.deltaY;view();}},{passive:false});
function zoom(scale,cx,cy){const r=viewport.getBoundingClientRect(),x=cx??r.left+r.width/2,y=cy??r.top+r.height/2,p=local({clientX:x,clientY:y});pan.scale=Math.max(.2,Math.min(3,scale));pan.x=x-r.left-p.x*pan.scale;pan.y=y-r.top-p.y*pan.scale;view();renderSelection();}
function cancelOcr(){requestId++;abort?.abort();abort=null;$('busy').hidden=true;editId=null;}
const recognitionCache=new Map();
async function runRecognition(){if(!selection)return;cancelOcr();const id=requestId,area=clone(selection),strokes=selectedStrokes(area);if(!strokes.length){toast('手書きの数式を囲んでください。');return;}let timer=setTimeout(()=>{if(id===requestId){$('busy').hidden=false;$('busy-text').textContent='読み取り中…';}},500);let longTimer=setTimeout(()=>{if(id===requestId)$('busy-text').textContent='認識を続けています';},2000);try{let recognized;const key=JSON.stringify([settings.provider,area,strokes]);if(recognitionCache.has(key))recognized=recognitionCache.get(key);else if(settings.provider==='local'){await new Promise(r=>requestAnimationFrame(r));recognized=recognize(strokes);}else{abort=new AbortController();const image=document.createElement('canvas');let scale=Math.min(2,1600/Math.max(area.w,area.h));image.width=Math.max(1,Math.ceil(area.w*scale+24));image.height=Math.max(1,Math.ceil(area.h*scale+24));const c=image.getContext('2d');c.fillStyle='#fff';c.fillRect(0,0,image.width,image.height);c.translate(12,12);c.scale(scale,scale);c.translate(-area.x,-area.y);c.beginPath();c.rect(area.x,area.y,area.w,area.h);c.clip();for(const s of strokes)stroke({...s,color:'#111'},c);const response=await fetch('./api/ocr',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({image:image.toDataURL('image/png')}),signal:abort.signal});const data=await response.json();if(!response.ok)throw Error(data.error||'認識に失敗しました。');recognized={...data,provider:'mathpix'};}
 if(id!==requestId)return;recognitionCache.set(key,recognized);if(recognitionCache.size>50)recognitionCache.delete(recognitionCache.keys().next().value);pending={area,recognized};let parsed;try{parsed=calculate(recognized.formula);}catch{}const threshold=settings.provider==='local'?.93:.92;
 if(recognized.confidence>=threshold&&parsed){addCalculation(recognized.formula,recognized.confidence,area,parsed,recognized.provider);selection=null;renderSelection();setTool('pen');toast('計算しました');}else showFormula(recognized.formula,'読み取った数式を確認',`${recognized.provider==='local'?'端末内認識の一致スコア':'OCR信頼度'} ${Math.round(recognized.confidence*100)}% · 読み取りに曖昧さがあります。`,false);
 }catch(e){if(id===requestId&&e.name!=='AbortError'){pending={area,recognized:{confidence:0,provider:settings.provider}};showFormula('','数式をうまく読み取れませんでした',e.message,false);}}finally{clearTimeout(timer);clearTimeout(longTimer);if(id===requestId)$('busy').hidden=true;}}
function addCalculation(formula,confidence,area,parsed,provider='manual'){checkpoint();if(editId){const old=page().calculations.find(c=>c.id===editId);if(old)Object.assign(old,{recognizedFormula:formula,...parsed,confidence,provider});}else page().calculations.push({id:uid(),selectionArea:area,recognizedFormula:formula,confidence,...parsed,provider,resultPosition:{x:Math.min(950,area?.x??110),y:Math.min(1640,area?area.y+area.h+14:Math.max(240,(bounds(page().strokes)?.y??0)+(bounds(page().strokes)?.h??0)+40,...page().calculations.map(c=>c.resultPosition.y+75)))},createdAt:new Date().toISOString()});editId=null;renderResults();changed();}
function renderResults(){$('results').replaceChildren();for(const c of page().calculations){const b=document.createElement('button');b.className=`result ${settings.style} ${c.answer.startsWith('x')?'equation':''}`;b.textContent=c.answer;b.style.left=c.resultPosition.x+'px';b.style.top=c.resultPosition.y+'px';b.setAttribute('aria-label',`${c.answer}、詳細を表示`);let drag=null,moved=false;b.onpointerdown=e=>{if(e.pointerType==='touch'&&penDown)return;e.stopPropagation();b.setPointerCapture(e.pointerId);const p=local(e);drag={p,origin:{...c.resultPosition},saved:false};moved=false;};b.onpointermove=e=>{if(!drag)return;const p=local(e);if(Math.hypot(p.x-drag.p.x,p.y-drag.p.y)>5/pan.scale){if(!drag.saved){checkpoint();drag.saved=true;}moved=true;}if(moved){c.resultPosition={x:Math.max(0,Math.min(1050,drag.origin.x+p.x-drag.p.x)),y:Math.max(0,Math.min(1640,drag.origin.y+p.y-drag.p.y))};b.style.left=c.resultPosition.x+'px';b.style.top=c.resultPosition.y+'px';}};b.onpointerup=e=>{e.stopPropagation();if(moved)changed();drag=null;};b.onpointercancel=()=>{if(drag?.saved){c.resultPosition=drag.origin;history.pop();renderResults();buttons();}drag=null;};b.onclick=()=>{if(moved){moved=false;return;}openDetail(c.id);};$('results').append(b);}}
function showFormula(value='',heading='数式を入力',message='四則演算・分数・百分率・一次方程式に対応しています。',manual=true){if(manual){pending=null;editId=null;cancelOcr();}$('formula').value=value;$('formula-heading').textContent=heading;$('formula-message').textContent=message;$('formula-error').textContent='';$('retry').hidden=!pending;$('reselect').hidden=!pending;$('formula-dialog').showModal();$('formula').focus();}
function openDetail(id){const c=page().calculations.find(c=>c.id===id);detailId=id;$('detail-source').textContent=c.recognizedFormula;$('steps').replaceChildren(...c.steps.map(text=>{const l=document.createElement('li');l.textContent=text;return l;}));$('detail-dialog').showModal();}
$('formula-form').onsubmit=e=>{e.preventDefault();try{const f=$('formula').value,result=calculate(f);addCalculation(f,pending?.recognized.confidence??1,pending?.area??null,result,pending?.recognized.provider??'manual');$('formula-dialog').close();selection=null;renderSelection();setTool('pen');}catch(err){$('formula-error').textContent=err.message;}};
$('manual').onclick=()=>showFormula();$('retry').onclick=()=>{$('formula-dialog').close();runRecognition();};$('reselect').onclick=()=>{$('formula-dialog').close();selection=null;renderSelection();setTool('select');};$('cancel').onclick=()=>{cancelOcr();toast('認識を中止しました。再選択して再実行できます。');};
$('delete-result').onclick=()=>{checkpoint();page().calculations=page().calculations.filter(c=>c.id!==detailId);$('detail-dialog').close();renderResults();changed();};$('recalculate').onclick=()=>{const c=page().calculations.find(c=>c.id===detailId);$('detail-dialog').close();showFormula(c.recognizedFormula,'数式を修正');editId=c.id;};
document.querySelectorAll('dialog .close').forEach(b=>b.onclick=()=>b.closest('dialog').close());document.querySelectorAll('[data-tool]').forEach(b=>b.onclick=()=>setTool(b.dataset.tool));document.querySelectorAll('[data-color]').forEach(b=>b.onclick=()=>{color=b.dataset.color;document.querySelectorAll('[data-color]').forEach(v=>v.classList.toggle('active',v===b));});$('width').oninput=e=>width=+e.target.value;$('undo').onclick=undo;$('redo').onclick=redo;$('save').onclick=async()=>{if(await save())toast('ノートを保存しました');};$('more').onclick=()=>$('settings-dialog').showModal();
$('title').addEventListener('focus',()=>checkpoint());$('title').oninput=e=>{doc.title=e.target.value;changed();};$('background').onchange=e=>{checkpoint();page().background.type=e.target.value;syncSettings();changed();};$('touch-write').onchange=e=>{settings.touch=e.target.checked;changed();};$('provider').onchange=e=>{cancelOcr();settings.provider=e.target.value;syncSettings();changed();};$('result-style').onchange=e=>{settings.style=e.target.value;renderResults();changed();};$('zoom-in').onclick=()=>zoom(pan.scale*1.2);$('zoom-out').onclick=()=>zoom(pan.scale/1.2);$('zoom-reset').onclick=fit;
$('example').onclick=()=>{checkpoint();let x=140;for(const ch of '12+34'){const lines=shapes[ch][0].split('|').map(line=>line.split(' ').map(p=>{const[a,b]=p.split(',').map(Number);return{x:x+a*4,y:260+b*5,p:.5};}));for(const pts of lines)page().strokes.push({id:uid(),points:pts,width:2.8,color:'#20333d'});x+=70;}draw();changed();setTool('select');toast('「12 + 34」をドラッグで囲んでください');};
$('export').onclick=()=>{const blob=new Blob([JSON.stringify({version:1,doc,settings},null,2)],{type:'application/json'});const url=URL.createObjectURL(blob),a=document.createElement('a');a.href=url;a.download='計算ノート-'+new Date().toISOString().slice(0,10)+'.json';a.click();setTimeout(()=>URL.revokeObjectURL(url),1000);};$('import').onclick=()=>$('import-file').click();
function validateDocument(d){if(!d||typeof d.title!=='string'||!Array.isArray(d.pages)||d.pages.length!==1)throw Error('対応していないノート形式です。');const p=d.pages[0];if(p.width!==1200||p.height!==1700||!['grid','plain','ruled'].includes(p.background?.type)||!Array.isArray(p.strokes)||!Array.isArray(p.calculations)||p.strokes.length>30000)throw Error('ノートの形式を確認してください。');for(const s of p.strokes){if(!Array.isArray(s.points)||s.points.length>100000||!Number.isFinite(s.width)||s.width<.1||s.width>50||!/^#[0-9a-f]{6}$/i.test(s.color))throw Error('筆跡データが不正です。');for(const pt of s.points)if(!Number.isFinite(pt.x)||!Number.isFinite(pt.y)||Math.abs(pt.x)>20000||Math.abs(pt.y)>20000)throw Error('座標が不正です。');}for(const c of p.calculations)if(typeof c.answer!=='string'||typeof c.recognizedFormula!=='string'||!Array.isArray(c.steps)||!c.steps.every(s=>typeof s==='string')||!Number.isFinite(c.resultPosition?.x)||!Number.isFinite(c.resultPosition?.y))throw Error('計算データが不正です。');}
$('import-file').onchange=async e=>{const file=e.target.files[0];if(!file)return;try{if(file.size>20e6)throw Error('20MB以下のバックアップを選んでください。');const data=JSON.parse(await file.text());validateDocument(data.doc);cancelOcr();checkpoint();doc=data.doc;selection=null;draw();renderResults();renderSelection();syncSettings();$('title').value=doc.title;changed();toast('復元しました。「取り消す」で元に戻せます。');}catch(err){toast(err.message);}e.target.value='';};
document.addEventListener('keydown',e=>{if(e.target.matches('input,textarea,select'))return;if((e.ctrlKey||e.metaKey)&&e.key.toLowerCase()==='z'){e.preventDefault();e.shiftKey?redo():undo();}if(e.key==='Escape'){cancelOcr();selection=null;renderSelection();}});document.addEventListener('visibilitychange',()=>{if(document.hidden&&ready)save();});window.addEventListener('resize',()=>{if(pan.x>viewport.clientWidth-80)fit();});
$('connection').textContent='この公開版は端末内認識を使用します。追加契約やAPIキーは不要です。'; $('provider').options[1].disabled=true;
if('serviceWorker'in navigator)navigator.serviceWorker.register('./sw.js').catch(()=>{});
if(document.modelContext?.registerTool){try{Promise.resolve(document.modelContext.registerTool({name:'calculate_formula',description:'数式を計算し、このノートに結果を追加します。',inputSchema:{type:'object',properties:{formula:{type:'string'}},required:['formula'],additionalProperties:false},annotations:{readOnlyHint:false,untrustedContentHint:false},execute:async input=>{if(!ready||!input||typeof input.formula!=='string')throw Error('有効な数式が必要です。');const result=calculate(input.formula);editId=null;addCalculation(input.formula,1,null,result);return{answer:result.answer};}})).catch(()=>{});}catch{}}
fit();openStorage();
